In [5]:
## This notebook is based on the youtube channel https://www.youtube.com/watch?v=tPYj3fFJGjk&t=71s

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.14.0


In [4]:
# print(tf.version)

## Data types

In [11]:
# integer
value=tf.Variable(123, tf.int16)
print(value)
print(value+2) # mathematical operations are applied on it

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=123>
tf.Tensor(125, shape=(), dtype=int32)


In [13]:
# float
float_val=tf.Variable(45.025, tf.float16)
print(float_val)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=45.025>


In [18]:
# string
str_val=tf.Variable("Ravi Kumar", tf.string)
print(str_val)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Ravi Kumar'>


In [19]:
string = tf.Variable("Ravi Kumar", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

In [23]:
print(string)
print(number)
print(floating)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Ravi Kumar'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.567>


In [24]:
# Above tensors are 0 degree/rank
# Below we create more than 0 degree tensor

## Rank/Degree of Tensor

In [25]:
rank1_tensor = tf.Variable(["Test"], tf.string)
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)

In [29]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [30]:
rank2_tensor.shape

TensorShape([2, 2])

## Array and reshape 

In [35]:
tensor1 = tf.ones([2,3,4])  # tf.ones() creates a shape [1,2,3] tensor full of ones
tensor2 = tf.reshape(tensor1, [8,3,1])  
tensor3 = tf.reshape(tensor2, [3, -1])  # -1 tells the tensor to calculate the size of the dimension in that place
                                        
# The nubmer of elements in the reshaped tensor MUST match the number in the original

In [42]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(2, 3, 4), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(8, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]], shape=(3, 8), dtype=float32)


In [43]:
## Different types to print

In [46]:
print(f"Tensor1: {tensor1}")

Tensor1: [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [47]:
print("Tensor1:",tensor1)

Tensor1: tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(2, 3, 4), dtype=float32)


## Define matrix and slicing

In [55]:
# Creating a 2D tensor
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

tensor = tf.Variable(matrix, dtype=tf.int32)
print(tensor)

<tf.Variable 'Variable:0' shape=(4, 5) dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])>


In [56]:
print(tf.rank(tensor))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


In [63]:
## Better way of printing and readable
print(f"Tensor:\n{tensor.read_value()}")
print(f"Rank of tensor: {tf.rank(tensor)}")
print(f"Shape of tensor: {tensor.shape}")

Tensor:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Rank of tensor: 2
Shape of tensor: (4, 5)


In [65]:
# Now lets select some different rows and columns from our tensor

three = tensor[0,2]  # selects the 3rd element from the 1st row
print(three)  # -> 3

row1 = tensor[0]  # selects the first row
print(row1)

column1 = tensor[:, 0]  # selects the first column
print(column1)

row_2_and_4 = tensor[1::2]  # selects second and fourth row
print(row_2_and_4)

column_1_in_row_2_and_3 = tensor[1:3, 0]
print(column_1_in_row_2_and_3)


tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)
tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)
tf.Tensor([ 6 11], shape=(2,), dtype=int32)


In [74]:
## Better way of printing and readable
print(f"Third element of the first row: {three}")
print(f"First row: {row1}")
print(f"First column: {column1}")
print(f"Second and fourth row:\n {row_2_and_4}")
print(f"First column in row second and fourth: {column_1_in_row_2_and_3}")

Third element of the first row: 3
First row: [1 2 3 4 5]
First column: [ 1  6 11 16]
Second and fourth row:
 [[ 6  7  8  9 10]
 [16 17 18 19 20]]
First column in row second and fourth: [ 6 11]
